### ISSUE TITLE
Immediate dissconnect due to non UTF bytes in connect response

### ISSUE THREAD

**Issue by alexmironof** [mtfelian/golang-socketio#10]
Hi! I'm trying to connect to `api.victra.io/stream` and got response with weird bytes attached to body 😢 

`base64`
```
AAEACf8weyJzaWQiOiI3OTkzMjg2NmNlY2M0MTUyYThlYjEzZWQ4NmQ3NjAxZSIsInVwZ3JhZGVzIjpbIndlYnNvY2tldCJdLCJwaW5nVGltZW91dCI6NjAwMDAsInBpbmdJbnRlcnZhbCI6MjUwMDB9AAL/NDA=
```
`raw`
```
	ÿ0{"sid":"79932866cecc4152a8eb13ed86d7601e","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}ÿ40
```

But `JavaScript` or `Python` clients works just fine 

Could not figure out how to completly remove this from response

**Comment by alexmironof** [comment]
I've managed to get it working here https://github.com/alexmironof/golang-socketio/commit/5b391c4427eed5b9017e099e5b3c702e154a636f

**Comment by mtfelian** [comment]
Sorry for the delay, but your issue description is not informative. Can you please create a PR to fix it? Please specify the problem in more detailed manner, when, what and why happens wrongly. 

Thank you!

**Comment by alexmironof** [comment]
@mtfelian thanks for the response!

I mean that external `socket.io` server sends all messages with some non-UTF8 bytes inside response body and `golang-socketio` client just could not parse it, cause it expects to get certain symbol at defined position as by protocol agreement.

What socket.io protocol version `golang-socketio` implements?

I think that PR would break all the things 😟 

Lates `python socket.io server` send massages like this ones:
- with weird non-UTF8 bytes
```
�	ÿ0{"sid":"79932866cecc4152a8eb13ed86d7601e","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}�ÿ40
```
- only UTF8 bytes
```
0{"sid":"79932866cecc4152a8eb13ed86d7601e","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}40
```

**Comment by alexmironof** [comment]
@mtfelian Yeas I definitely will make at least to small PRs: one for trimming non-UTF bytes and another for transforming response message "ok" to uppercase and comparing against it.

> Do you mean "it" is a python server 
Yes I do.

I dont know why, but latest JavaScript and Python `socket.io` client libraries works just fine with that server software.
It runs live here http://victra.io/stream.html

Also I asked Victra developers about their `socket.io` server software.

P.S. I forgot to mention that I'm using 'LongPolling' `http` method  instead of `ws` and I could check out `ws` later

**Comment by mtfelian** [comment]
> P.S. I forgot to mention that I'm using 'LongPolling' http method instead of ws and I could check out ws later

e.g. all that you written above was about  `this` client via polling transport (`PollingClientConnection`) ?

Thanks for participating.

**Comment by alexmironof** [comment]
@mtfelian 

> e.g. all that you written above was about this client via polling transport (PollingClientConnection) ? :) 

Actually yes 😅  Sorry, `socket.io` drives me crazy )))

So I made some reverse engineering and found something interesting:
I guess that `socket.io` server could both send payloads in binary and string format and client would parse both

Actually this is a function for parsing binary https://github.com/socketio/engine.io-client/blob/master/engine.io.js#L2333

So I debug `socket.io.js` at Victra and understand what is going on:
First I got response payload from server as ByteArray
`bufferTail = [0,1,0,9,255,48,123,34,115,105,100,34,58,34,55,48,52,56,50,53,99,102,99,49,101,55,52,53,98,56,98,48,54,48,98,56,54,51,50,98,101,51,98,53,48,98,34,44,34,117,112,103,114,97,100,101,115,34,58,91,34,119,101,98,115,111,99,107,101,116,34,93,44,34,112,105,110,103,84,105,109,101,111,117,116,34,58,54,48,48,48,48,44,34,112,105,110,103,73,110,116,101,114,118,97,108,34,58,50,53,48,48,48,125,0,2,255,52,48]`

- `String.fromCharCode(48) = "0"`
- `String.fromCharCode(123) = "{"` 
- `String.fromCharCode(125) = "}"` 
- `bufferTail.length = 119`

`decodePayloadAsBinary` function starts iterating through array from `index = 1` till it finds `bufferTail[index] == 255` and concatenating iterated bytes. Result would be string `msgLength = "109"`.

Then this code happens:

```
// Slice bufferTail from index 5
// slicedPart = [0,1,0,9,255]
// slicedPart.length = 5
// bufferTail = [48,123.....125,0,2,255,52,48]
// bufferTail.length = 114
bufferTail = sliceBuffer(bufferTail, 2 + msgLength.length);
msgLength = parseInt(msgLength);
// Then slice bufferTail to index 109
// bufferTail = [48,123.....125]
// bufferTail.length = 109
// slicedPart = [0,2,255,52,48]
// slicedPart.length = 5
// String.fromCharCode(52) = "4"
// String.fromCharCode(48) = "0"
var msg = sliceBuffer(bufferTail, 0, msgLength);
```
Phew 😓 
This magical, undocumented, hardly readable and almost not understandable code do the job

Then I guess it extracts somewhere else message `40` and everything goes smooth

So when I've just trim out of payload all non-UTF8 bytes I've made it just work for me...
I'll try to implement this logic, but I need to dig into more deeply to understand how JavaScript implementation deals with this last two bytes containing message `"40"` and how it realises that there is one message in stead of two expected

**Comment by alexmironof** [comment]
Also I'll try to check `ws` but I guess I'll receive the same payload as from `http`

**Comment by mtfelian** [comment]
@alexmironof how are you about this issue? :)

**Comment by alexmironof** [comment]
@mtfelian I guess unfortunately it's not on my schedule for now 😅 

I'll close it, and when I find some time, I'll implement `socket-io-client.js` logic here.
