### ISSUE TITLE
wss connection problem / bad handshake

### ISSUE THREAD

**Issue by varun1729** [mtfelian/golang-socketio#13]
`x509: certificate is valid for <localhost>, not <remote host>`

Any ideas on what may be causing this?
I am connecting using the `wss` protocol.
Connecting like so:
`client, err := gosocketio.Dial("wss://"+host+"/test/socket.io", transport.DefaultWebsocketTransport())`

I wont't be surprised if this is a Docker issue with my remote host... and not on golang-socket.io side...

**Comment by mtfelian** [comment]
You need to provide the right certificate or pass InsecureSkipVerify true to the underlying http tls. If you using Docker may be you need any intermediate configuration. Did not tried it.

**Comment by mtfelian** [comment]
You need to provide the right certificate or pass `InsecureSkipVerify: true` to the underlying http tls. If you using Docker may be you need any intermediate configuration. Did not tried it.

**Comment by varun1729** [comment]
How do I specify 

something like this 
```
// insecureTransport := transport.DefaultWebsocketTransport()
	// insecureTransport.TLSClientConfig = &tls.Config{
	// 	InsecureSkipVerify: true,
	// }
```
on

```
type WebsocketTransport struct {
	PingInterval   time.Duration
	PingTimeout    time.Duration
	ReceiveTimeout time.Duration
	SendTimeout    time.Duration

	BufferSize int
	Headers    http.Header
}
```

**Comment by mtfelian** [comment]
Yes but now it is unsupported, you can make a PR with this change. 

We have a method `NewWebsocketTransport` which receives parameters. Add `*tls.Config` as a new field to that params. Next you can pass it to the `websocket.Dialer` inside `Connect` method in client. 

Also it will be good to implement it for the polling transport.

**Comment by varun1729** [comment]
I will work on it.

**Comment by varun1729** [comment]
PR 15 ready to solve this, however I now  get an 
```
websocket: bad handshake
```
Whether its our package or Docker remains to be solved...

**Comment by mtfelian** [comment]
> PR 15 ready to solve this, however I now get an
> 
> ```
> websocket: bad handshake
> ```
> Whether its our package or Docker remains to be solved...

In order to understand the problem please provide a code for your client and a working server. The problem may lie in bad config, in CORS, in some ws issue or something other.

**Comment by varun1729** [comment]
Client Side URL
```
wssURL := "wss://" + host + "/test/socket.io/"
	infoPrint("URL:", wssURL)
	client, err := gosocketio.Dial(wssURL, transport.NewWebsocketTransport(transport.WebsocketTransportParams{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}))
```

Server side
```
socketServer = gosocketio.NewServer()
testRouter.Handle("/socket.io/", socketServer)
```

**Comment by mtfelian** [comment]
Now please dump entire headers. Use the httptest package in go server side
for it.

**Comment by varun1729** [comment]
This is the HTTP request arriving to server:
```
"GET /test/socket.io/ HTTP/1.1\r\nHost: acme.cicd.continube.co\r\nConnection: Upgrade\r\nSec-Websocket-Key: U37VzWk09EftpE3zUnWyWw==\r\nSec-Websocket-Version: 13\r\nUpgrade: websocket\r\nUser-Agent: Go-http-client/1.1\r\n\r\n"
```
