### ISSUE TITLE
Why HTTP code 403 when upgrading to websockets?

### ISSUE THREAD

**Issue by Xsander** [mtfelian/golang-socketio#8]
Hi. I'm trying to use your lib with gin, so I've set up a server , and trying to connect with javascript client using latest socket.io-client package. It works only on transport "polling". When trying to upgrade to web sockets, it shows next:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/5268283/42380104-717c24a2-8135-11e8-9b71-60f233d3197e.png">

My server code:

```
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/mtfelian/golang-socketio"
)

func main() {
	router := gin.Default()
	sio := gosocketio.NewServer()
	router.GET("/socket.io/", gin.WrapH(sio))
	router.POST("/socket.io/", gin.WrapH(sio))
	router.Run(":7000")

}

```

When I use latest socket.io server on NodeJS, it upgrades fine.

**Comment by mtfelian** [comment]
@Xsander Please try the following code: 
```
// GET for WS and XHR polling transports
router.Handle("GET", "/socket.io/", func(c *gin.Context) { sio.ServeHTTP(c.Writer, c.Request) })
// POST is only for XHR polling transport
router.Handle("POST", "/socket.io/", func(c *gin.Context) { sio.ServeHTTP(c.Writer, c.Request) })
```
but seems to be identical with `WrapH()`. 

Please provide the JS client testing code and I'll check it. 

The debug output in your screenshot tells that HTTP 403 (Forbidden) appeared from somewhere, so first we should deal with it. 

Does it work if you specify the single websocket transport in your JS client ?

**Comment by mtfelian** [comment]
Also the problem may lie in websocket `Upgrader` calling `CheckOrigin()` as described here: http://www.gorillatoolkit.org/pkg/websocket

If it's it, you can try adding a CORS middleware to you Gin, for example like this: https://github.com/gin-contrib/cors

**Comment by Xsander** [comment]
damn, sorry, i'm blind. There is 503 instead of 403 code. And i found another error in my code, it's so stupid, i have two domain names on that server, and opened widget with socket client on one domain, and it was connecting to another. Thanks, seems all is working. Your library is the only one which is working and up to date. Thanks for your work!

**Comment by mtfelian** [comment]
@Xsander thanks for the confidence, enhancements appreciated.
